name: ShopKeepers-NexoAddon
version: '1.0.1'
main: dev.waterchick.shopKeepersNexoAddon.ShopKeepersNexoAddon
api-version: '1.20'
depend: [Shopkeepers, Nexo]
authors: [ Water_Chick ]
website: https://waterchick.dev
